---
- name: Disks playbook
  hosts: dbservers
  become: yes
  tasks:
    - name: Create Volume Group
      lvg:
        vg: RHCE
        pvs: /dev/xvdg
    - name: Create Logical volume
      lvol:
        lv: AppDB2
        vg: RHCE
        size: 10G
        pvs: /dev/xvdg
        state: present
    - name: format disk
      filesystem:
        dev: /dev/RHCE/AppDB2
        fstype: xfs
    - name: mount disk
      mount:
        fstype: xfs
        src: /dev/RHCE/AppDB2
        state: mounted
        path: /mnt/AppDB2
