## Service Module
#- name: Show options for service module
#  service:
#    name: service_name
#    state: started | stopped | restarted | reloaded
#    enabled: yes | no
#    args: additional argu provided on the command line
#
 
## Systemd
#- name: Show options for systemd module
#  systemd:
#    name: service_name
#    state: started | stopped | restarted | reloaded
#    enabled: yes | no
#    daemon_reload: yes | no
#    force: yes | no

---
- hosts: webservers with service
  become: yes
  tasks:
    - name: start and enable httpd
      service:
        name: httpd
        state: started
        enabled: yes
    - name: start and enable firewalld
      service:
        name: firewalld
        state: started
        enabled: yes

- hosts: webservers with systemd
  become: yes
  tasks:
    - name: start and enable httpd
      systemd:
        name: httpd
        state: restarted
        enabled: yes
    - name: start and enable firewalld
      systemd:
        name: firewalld
        state: restarted
        enabled: yes
