# Template
# Variables
# notify
# handler
---
- hosts: webservers
  become: yes
  vars:
    content_dir: /webcontent
    http_port: 8080
    admin: cloud_user
  tasks:
    - name: push httpd template
      template:
        src: /home/galal/ansible/templates/httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf
        backup: yes
      notify: "restart apache"
    - name: push index.html
      template:
        src: /home/galal/ansible/templates/indec.html.j2
        dest: /webcontent/index.html
  handlers:
    - name: restart web server
      service:
        name: httpd
        state: restarted
      listen: "restart apache"
