---
- hosts: webservers
  become: yes

  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present
    - name: Enable and start httpd
      service:
        name: httpd
        enabled: yes
        state: started

